# Generated by Django 4.0.4 on 2022-05-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beat_track', '0002_alter_audio_audio_alter_audio_resultsec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio',
            field=models.FileField(upload_to='Users/amir/Desktop/audioanalize/audiofiles'),
        ),
    ]
