# Generated by Django 4.0.4 on 2022-05-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beat_track', '0003_alter_audio_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='image',
            field=models.ImageField(blank=True, upload_to='Users/amir/Desktop/audioanalize/audiofiles'),
        ),
    ]
